name: Docker

on:
  schedule:
    - cron: '24 14 * * *'
  push:
    branches: [ main ]
    # Publish semver tags as releases.
    # tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker QEMU
        id: qemu
        uses: docker/setup-qemu-action@2d4bfe71c9c7c6adb935665efb1a651cc8e799ba

      - name: Available platforms
        run: echo ${{ steps.qemu.outputs.platforms }}
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      - name: Log in to Docker Hub
        uses: docker/login-action@1edf6180e07d2ffb423fc48a1a552855c0a1f508
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

