name: Docker

on:
  schedule:
    - cron: '24 14 * * *'
  push:
    branches: [ main ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

env:
  GDB_VERSION: 11.2

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup gdb & buildroot env
        run: |
          sudo chmod +x ./setup_env.sh && sudo ./setup_env.sh $GDB_VERSION
      
      - name: arm cross building
        run: |
          sudo chmod +x ./builder.sh && sudo ./builder.sh $GDB_VERSION arm

